server:
  port: 8858
  servlet:
    context-path: /bank
    
spring:
  application:
    name: bank-customer-service
    
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankservice
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    #    - health
    
  endpoint:
    health:
      show-details: always
      
    
# Register with Eureka Service
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      
      
#Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      creditscore-service:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: count-based